version: "3.8"

networks:
  AlphaNet:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpha_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - AlphaNet

  nginx:
    image: nginx:alpine
    container_name: alpha_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - AlphaNet    
  mysql:
    image: "${MYSQL_IMAGE}"
    container_name: "${MYSQL_CONTAINER_NAME}"
    restart: "${MYSQL_RESTART_MODE}"
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - AlphaNet

  phpmyadmin:
    image: "${PMA_IMAGE}"
    container_name: "${PMA_CONTAINER_NAME}"
    restart: "${PMA_RESTART_MODE}"
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - mysql
    networks:
      - AlphaNet
